const ADD_TODO = "ADD_TODO";
const TOGGLE_TODO = "TOGGLE_TODO";
const SET_VISIBILITY_FILTER = "SET_VISIBILITY_FILTER";

export const MODELS = {
  TODO_MODELS: {
    ADD_TODO: ADD_TODO,
    TOGGLE_TODO: TOGGLE_TODO
  },
  FILTER_MODELS: {
    SET_VISIBILITY_FILTER: SET_VISIBILITY_FILTER
  }
};
