const GET_USERS = "GET_USERS";
const GET_ALBUM = "GET_ALBUM";
const DELETE_USER = "DELETE_USER";
const POST_USER = "POST_USER";
const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
// const LOAD_USERS_LOADING = 'LOAD_USERS_LOADING';
// const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS'
// const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR'



export const ACTIONS = {
  GET_USERS,
  GET_ALBUM,
  DELETE_USER,
  POST_USER,
  UPDATE_USER,
  LOAD_USERS_ERROR,
  LOAD_USERS_LOADING,
  LOAD_USERS_SUCCESS
};
