const AXIOS_GET_USERS = "AXIOS_GET_USERS";
const AXIOS_POST_USERS = "AXIOS_POST_USERS";
const AXIOS_GET_ALBUM = 'AXIOS_GET_ALBUM';
const AXIOS_DELETE_USER = 'AXIOS_DELETE_USER';


export default { AXIOS_GET_USERS, AXIOS_POST_USERS, AXIOS_GET_ALBUM, AXIOS_DELETE_USER}
