const FETCH_API_REQUEST = "FETCH_API_REQUEST";
const FETCH_API_SUCCESS = "FETCH_API_SUCCESS";
const FETCH_API_FAIL = "FETCH_API_FAIL";
const CREATE_API_REQUEST = "CREATE_API_REQUEST";
const CREATE_API_SUCCESS = "CREATE_API_SUCCESS";
const CREATE_API_FAIL = "CREATE_API_FAIL";
const DELETE_API_REQUEST = "DELETE_API_REQUEST";
const DELETE_API_SUCCESS = "DELETE_API_SUCCESS";
const DELETE_API_FAIL = "DELETE_API_FAIL";
const UPDATE_API_REQUEST = "UPDATE_API_REQUEST";
const UPDATE_API_SUCCESS = "UPDATE_API_SUCCESS";
const UPDATE_API_FAIL = "UPDATE_API_FAIL";

const FETCH_ACTIONS_API_REQUEST = "FETCH_ACTIONS_API_REQUEST";
const FETCH_ACTIONS_API_SUCCESS = "FETCH_ACTIONS_API_SUCCESS";
const FETCH_ACTIONS_API_FAIL = "FETCH_ACTIONS_API_FAIL";
const CREATE_ACTION_API_REQUEST = "CREATE_ACTION_API_REQUEST";
const CREATE_ACTION_API_SUCCESS = "CREATE_ACTION_API_SUCCESS";
const CREATE_ACTION_API_FAIL = "CREATE_ACTION_API_FAIL";
const DELETE_ACTION_API_REQUEST = "DELETE_ACTION_API_REQUEST";
const DELETE_ACTION_API_SUCCESS = "DELETE_ACTION_API_SUCCESS";
const DELETE_ACTION_API_FAIL = "DELETE_ACTION_API_FAIL";
const UPDATE_ACTION_API_REQUEST = "UPDATE_ACTION_API_REQUEST";
const UPDATE_ACTION_API_SUCCESS = "UPDATE_ACTION_API_SUCCESS";
const UPDATE_ACTION_API_FAIL = "UPDATE_ACTION_API_FAIL";

export default {
  FETCH_API_FAIL,
  FETCH_API_REQUEST,
  FETCH_API_SUCCESS,
  CREATE_API_FAIL,
  CREATE_API_REQUEST,
  CREATE_API_SUCCESS,
  DELETE_API_FAIL,
  DELETE_API_REQUEST,
  DELETE_API_SUCCESS,
  UPDATE_API_REQUEST,
  UPDATE_API_SUCCESS,
  UPDATE_API_FAIL,
  FETCH_ACTIONS_API_FAIL,
  FETCH_ACTIONS_API_REQUEST,
  FETCH_ACTIONS_API_SUCCESS,
  CREATE_ACTION_API_FAIL,
  CREATE_ACTION_API_REQUEST,
  CREATE_ACTION_API_SUCCESS,
  DELETE_ACTION_API_FAIL,
  DELETE_ACTION_API_REQUEST,
  DELETE_ACTION_API_SUCCESS,
  UPDATE_ACTION_API_FAIL,
  UPDATE_ACTION_API_REQUEST,
  UPDATE_ACTION_API_SUCCESS
};
