const FETCH_PROJECT_REQUEST = "FETCH_PROJECT_REQUEST";
const FETCH_PROJECT_SUCCESS = "FETCH_PROJECT_SUCCESS";
const FETCH_PROJECT_FAIL = "FETCH_PROJECT_FAIL";
const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
const CREATE_PROJECT_SUCCESS = "CREATE_PROJECT_SUCCESS";
const CREATE_PROJECT_FAIL = "CREATE_PROJECT_FAIL";
const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";
const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";
const UPDATE_PROJECT_REQUEST = "UPDATE_PROJECT_REQUEST";
const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";
const UPDATE_PROJECT_FAIL = "UPDATE_PROJECT_FAIL";

export default {
  FETCH_PROJECT_FAIL,
  FETCH_PROJECT_REQUEST,
  FETCH_PROJECT_SUCCESS,
  CREATE_PROJECT_FAIL,
  CREATE_PROJECT_REQUEST,
  CREATE_PROJECT_SUCCESS,
  DELETE_PROJECT_FAIL,
  DELETE_PROJECT_REQUEST,
  DELETE_PROJECT_SUCCESS,
  UPDATE_PROJECT_REQUEST,
  UPDATE_PROJECT_SUCCESS,
  UPDATE_PROJECT_FAIL
};