const FETCH_TABLE_REQUEST = "FETCH_TABLE_REQUEST";
const FETCH_TABLE_SUCCESS = "FETCH_TABLE_SUCCESS";
const FETCH_TABLE_FAIL = "FETCH_TABLE_FAIL";
const CREATE_TABLE_REQUEST = "CREATE_TABLE_REQUEST";
const CREATE_TABLE_SUCCESS = "CREATE_TABLE_SUCCESS";
const CREATE_TABLE_FAIL = "CREATE_TABLE_FAIL";
const DELETE_TABLE_REQUEST = "DELETE_TABLE_REQUEST";
const DELETE_TABLE_SUCCESS = "DELETE_TABLE_SUCCESS";
const DELETE_TABLE_FAIL = "DELETE_TABLE_FAIL";
const UPDATE_TABLE_REQUEST = "UPDATE_TABLE_REQUEST";
const UPDATE_TABLE_SUCCESS = "UPDATE_TABLE_SUCCESS";
const UPDATE_TABLE_FAIL = "UPDATE_TABLE_FAIL";

const FETCH_TYPES_TABLE_REQUEST = "FETCH_TYPES_TABLE_REQUEST";
const FETCH_TYPES_TABLE_SUCCESS = "FETCH_TYPES_TABLE_SUCCESS";
const FETCH_TYPES_TABLE_FAIL = "FETCH_TYPES_TABLE_FAIL";
const CREATE_TYPE_TABLE_REQUEST = "CREATE_TYPE_TABLE_REQUEST";
const CREATE_TYPE_TABLE_SUCCESS = "CREATE_TYPE_TABLE_SUCCESS";
const CREATE_TYPE_TABLE_FAIL = "CREATE_TYPE_TABLE_FAIL";
const DELETE_TYPE_TABLE_REQUEST = "DELETE_TYPE_TABLE_REQUEST";
const DELETE_TYPE_TABLE_SUCCESS = "DELETE_TYPE_TABLE_SUCCESS";
const DELETE_TYPE_TABLE_FAIL = "DELETE_TYPE_TABLE_FAIL";
const UPDATE_TYPE_TABLE_REQUEST = "UPDATE_TYPE_TABLE_REQUEST";
const UPDATE_TYPE_TABLE_SUCCESS = "UPDATE_TYPE_TABLE_SUCCESS";
const UPDATE_TYPE_TABLE_FAIL = "UPDATE_TYPE_TABLE_FAIL";

export default {
  FETCH_TABLE_FAIL,
  FETCH_TABLE_REQUEST,
  FETCH_TABLE_SUCCESS,
  CREATE_TABLE_FAIL,
  CREATE_TABLE_REQUEST,
  CREATE_TABLE_SUCCESS,
  DELETE_TABLE_FAIL,
  DELETE_TABLE_REQUEST,
  DELETE_TABLE_SUCCESS,
  UPDATE_TABLE_REQUEST,
  UPDATE_TABLE_SUCCESS,
  UPDATE_TABLE_FAIL,
  FETCH_TYPES_TABLE_FAIL,
  FETCH_TYPES_TABLE_REQUEST,
  FETCH_TYPES_TABLE_SUCCESS,
  CREATE_TYPE_TABLE_FAIL,
  CREATE_TYPE_TABLE_REQUEST,
  CREATE_TYPE_TABLE_SUCCESS,
  DELETE_TYPE_TABLE_FAIL,
  DELETE_TYPE_TABLE_REQUEST,
  DELETE_TYPE_TABLE_SUCCESS,
  UPDATE_TYPE_TABLE_REQUEST,
  UPDATE_TYPE_TABLE_SUCCESS,
  UPDATE_TYPE_TABLE_FAIL
};
