const API_CALL_REQUEST = "API_CALL_REQUEST";
const API_CALL_SUCCESS = "API_CALL_SUCCESS";
const API_CALL_FAILURE = "API_CALL_FAILURE";

const API_LOAD_MORE = "API_LOAD_MORE";
const API_LOAD_MORE_SUCCESS = "API_LOAD_MORE_SUCCESS";
const API_LOAD_MORE_FAILURE = "API_LOAD_MORE_FAILURE";

const POST_COMMENT = "POST_COMMENT";
const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
const POST_COMMENT_FAILURE = "POST_COMMENT_FAILURE";

const DELETE_COMMENT = "DELETE_COMMENT"
const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE"

const UPDATE_COMMENT = "UPDATE_COMMENT"
const UPDATE_COMMENT_SUCCESS = "UPDATE_COMMENT_SUCCESS"
const UPDATE_COMMENT_FAILURE = "UPDATE_COMMENT_FAILURE"

export const ACTIONS = {
  API_CALL_FAILURE,
  API_CALL_REQUEST,
  API_CALL_SUCCESS,
  API_LOAD_MORE,
  API_LOAD_MORE_SUCCESS,
  API_LOAD_MORE_FAILURE,
  POST_COMMENT,
  POST_COMMENT_FAILURE,
  POST_COMMENT_SUCCESS,
  DELETE_COMMENT,
  DELETE_COMMENT_FAILURE,
  DELETE_COMMENT_SUCCESS,
  UPDATE_COMMENT,
  UPDATE_COMMENT_SUCCESS,
  UPDATE_COMMENT_FAILURE
};
